@startuml

abstract class Window {
- mWindowManager : WindowManager
+setWindowManager()
}

class PhoneWindow{
    +setWindowManager()
}

interface ViewManager{
    +addView()
    +updateViewLayout()
    +removeView()
}

interface WindowManager{
    +class LayoutParams{}
    +addView()
    +updateViewLayout()
    +removeView()
}

class WindowManagerImpl{
    -WindowManagerGlobal mGlobal
    +addView()
    +updateViewLayout()
    +removeView()
}

Window<|--  PhoneWindow
ViewManager <|-- WindowManager
WindowManager <-- Window
WindowManager<|..  WindowManagerImpl

@enduml