@startuml

class HomeVoltage{
    + getHomeVoltage()
}
interface MobilePhoneVoltage{
    + getMobilePhoneVoltage()
}
class VoltageClassAdapter{
    + getHomeVoltage()
    + getMobilePhoneVoltage()
}
HomeVoltage <|-- VoltageClassAdapter
MobilePhoneVoltage <|.. VoltageClassAdapter
@enduml